version: "3.7"

services:
  caddy:
    image: caddy:2.3.0
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - $PWD/services/caddy/Caddyfile:/etc/caddy/Caddyfile

  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - "NODOS_HOST=0.0.0.0"
    ports:
      - "0.0.0.0:8080:8080"
    command: npm start
    volumes:
      - ./:/app
