version: "3.7"

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: "${NODOS_DB_USERNAME}"
      POSTGRES_PASSWORD: "${NODOS_DB_PASSWORD}"
      POSTGRES_HOST_AUTH_METHOD: trust

  app:
    build:
      context: .
      dockerfile: Dockerfile.production
    command: npm test
    depends_on:
      - db
